### ISSUE TITLE
make fails on OSX 10.6

### ISSUE THREAD

**Issue by telemachus** [c9s/cpansearch#1]
A first try failed on OSX 10.6.4 - seems to be an arch issue (x86_64). (See [here](http://gist.github.com/521756) for the output.)

All was fine after I removed membuf.o and ran `make` again.

**Comment by telemachus** [comment]
Hmm, spoke too soon. It builds, but I can't get past an initial sourcing of the mirror: [output](http://gist.github.com/521801).

Let me know if I can debug more usefully. I'm not sure what to check even.

**Comment by c9s** [comment]
sorry for the membuf.o... XD
I've remove the object file.

seems it's broken when transforming source list... I will take a look.

**Comment by c9s** [comment]
Hi ! i fixed it on 10.6.  please try again. :-)

**Comment by telemachus** [comment]
Yup, all good now (and the setup instructions on the readme are fuller too). Thanks for this.
